#!/bin/bash
# VCF PCA Analysis Deployment Guide
# For processing the 40GB VCF file efficiently

echo "==================================================================="
echo "VCF PCA Analysis Deployment Guide"
echo "==================================================================="

# Define paths
VCF_PATH="/mnt/czi-sci-ai/intrinsic-variation-gene-ex/wgs/data/variants/all_vcfs/merged.all.biallelic.maf0.01.vcf.gz"
OUTPUT_DIR="vcf_pca_production_results"
SCRIPTS_DIR="/mnt/czi-sci-ai/intrinsic-variation-gene-ex/wgs"

echo "📁 VCF file: $VCF_PATH"
echo "📊 Output directory: $OUTPUT_DIR"
echo ""

# Check if bcftools is available
if command -v bcftools &> /dev/null; then
    echo "✅ bcftools is available"
    BCFTOOLS_AVAILABLE=1
else
    echo "❌ bcftools not found - will use zcat approach"
    BCFTOOLS_AVAILABLE=0
fi

echo ""
echo "==================================================================="
echo "DEPLOYMENT OPTIONS"
echo "==================================================================="

echo ""
echo "🚀 OPTION 1: Quick Test Analysis (Recommended First)"
echo "-------------------------------------------------------------------"
echo "# Extract first 2000 variants for quick validation"
if [ $BCFTOOLS_AVAILABLE -eq 1 ]; then
    echo "bcftools view $VCF_PATH | head -2200 > quick_test.vcf"
else
    echo "zcat $VCF_PATH | head -2200 > quick_test.vcf"
fi
echo "python3 $SCRIPTS_DIR/real_vcf_pca_analysis.py --vcf-path quick_test.vcf --max-variants 2000 --output-dir quick_test_results"
echo ""

echo "🧬 OPTION 2: Chromosome-Specific Analysis"
echo "-------------------------------------------------------------------"
echo "# Process individual chromosomes for manageable analysis"
for chr in chr1 chr2 chr22; do
    echo "# Chromosome $chr:"
    if [ $BCFTOOLS_AVAILABLE -eq 1 ]; then
        echo "bcftools view -r $chr $VCF_PATH | head -10000 > ${chr}_subset.vcf"
    else
        echo "zcat $VCF_PATH | grep -E '^#|^$chr\\s' | head -10000 > ${chr}_subset.vcf"
    fi
    echo "python3 $SCRIPTS_DIR/real_vcf_pca_analysis.py --vcf-path ${chr}_subset.vcf --chromosome $chr --max-variants 8000 --output-dir ${chr}_pca_results"
    echo ""
done

echo "🏭 OPTION 3: Production Analysis (Requires HPC)"
echo "-------------------------------------------------------------------"
echo "# Full analysis - requires significant computational resources"
echo "# Recommended: 32+ GB RAM, 8+ cores"
echo "python3 $SCRIPTS_DIR/real_vcf_pca_analysis.py \\"
echo "  --vcf-path $VCF_PATH \\"
echo "  --chromosome chr1 \\"
echo "  --max-variants 50000 \\"
echo "  --n-components 20 \\"
echo "  --output-dir production_chr1_results"
echo ""

echo "📊 OPTION 4: Multi-Chromosome Parallel Processing"
echo "-------------------------------------------------------------------"
echo "# Process multiple chromosomes in parallel"
echo "# Create job array for HPC systems"
echo "# chromosomes=(chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr21 chr22)"
echo "# for chr in \"\${chromosomes[@]}\"; do"
echo "#   sbatch --job-name=pca_\$chr \\"
echo "#          --mem=16G \\"
echo "#          --cpus-per-task=4 \\"
echo "#          --wrap=\"python3 $SCRIPTS_DIR/real_vcf_pca_analysis.py --chromosome \$chr --max-variants 20000 --output-dir \${chr}_results\""
echo "# done"
echo ""

echo "==================================================================="
echo "RESOURCE REQUIREMENTS"
echo "==================================================================="
echo ""
echo "💾 Memory Requirements:"
echo "  • Quick test (2K variants):     4-8 GB RAM"
echo "  • Chromosome subset (10K):      8-16 GB RAM"  
echo "  • Large analysis (50K):         16-32 GB RAM"
echo "  • Full genome analysis:         32-64 GB RAM"
echo ""
echo "⏱️  Time Estimates:"
echo "  • Quick test:                   5-10 minutes"
echo "  • Single chromosome:            30-60 minutes"
echo "  • Large analysis:               2-4 hours"
echo "  • Full genome:                  6-12 hours"
echo ""
echo "🖥️  Recommended Environment:"
echo "  • HPC cluster or high-memory server"
echo "  • bcftools installed for efficient VCF handling"
echo "  • Python 3.8+ with scipy stack"
echo "  • 100+ GB disk space for intermediate files"
echo ""

echo "==================================================================="
echo "SAMPLE EXECUTION COMMANDS"
echo "==================================================================="
echo ""
echo "# 1. Quick validation (start here):"
echo "cd $SCRIPTS_DIR"
echo "python3 quick_vcf_pca.py  # Uses synthetic data"
echo ""
echo "# 2. Real data test:"
echo "python3 real_vcf_pca_analysis.py --chromosome chr22 --max-variants 1000 --output-dir chr22_test"
echo ""
echo "# 3. Production run:"
echo "python3 real_vcf_pca_analysis.py --chromosome chr1 --max-variants 20000 --n-components 15 --output-dir chr1_production"
echo ""

echo "==================================================================="
echo "EXPECTED OUTPUTS"
echo "==================================================================="
echo ""
echo "📈 Visualizations:"
echo "  • real_vcf_pca_ancestry.png      - Main PCA plot by ancestry"
echo "  • real_vcf_pca_populations.png   - Detailed population structure"
echo "  • real_vcf_pca_multicomponent.png - Multi-PC analysis"
echo "  • real_vcf_pca_dashboard.png     - Summary dashboard"
echo ""
echo "📊 Data Files:"
echo "  • real_vcf_pca_results.csv       - PCA coordinates & metadata"
echo "  • analysis_report.txt            - Detailed analysis summary"
echo ""
echo "🎯 Expected Results:"
echo "  • Clear separation of continental ancestry groups"
echo "  • PC1: ~10-15% variance (EUR vs AFR separation)"
echo "  • PC2: ~3-8% variance (EAS distinction)"
echo "  • Successful ancestry mapping for MAGE samples"
echo ""

echo "==================================================================="
echo "TROUBLESHOOTING"
echo "==================================================================="
echo ""
echo "🐛 Common Issues:"
echo ""
echo "1. Memory Error:"
echo "   → Reduce --max-variants parameter"
echo "   → Use chromosome-specific analysis"
echo "   → Increase system memory allocation"
echo ""
echo "2. Timeout/Slow Processing:"
echo "   → Install bcftools for faster VCF processing"
echo "   → Use SSD storage for temporary files"
echo "   → Process smaller chromosomes first (chr22, chr21)"
echo ""
echo "3. No Ancestry Mapping:"
echo "   → Check sample ID formats in VCF"
echo "   → Verify MAGE ancestry files are accessible"
echo "   → Review sample overlap between VCF and ancestry data"
echo ""
echo "4. Empty Results:"
echo "   → Verify VCF file integrity"
echo "   → Check chromosome naming convention (chr1 vs 1)"
echo "   → Ensure sufficient variants pass filtering"
echo ""

echo "==================================================================="
echo "✅ DEPLOYMENT GUIDE COMPLETE"
echo "==================================================================="
echo ""
echo "🚀 Ready to proceed with VCF-based PCA analysis!"
echo "💡 Start with OPTION 1 (Quick Test) to validate the pipeline"
echo "📧 All scripts and documentation are ready for deployment"
echo ""